# --- S3A / MinIO ---
spark.hadoop.fs.s3a.endpoint                    http://minio:9000
spark.hadoop.fs.s3a.access.key                  ${MINIO_ACCESS_KEY}
spark.hadoop.fs.s3a.secret.key                  ${MINIO_SECRET_KEY}
spark.hadoop.fs.s3a.path.style.access           true
spark.hadoop.fs.s3a.connection.ssl.enabled      false
spark.hadoop.fs.s3a.impl                        org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.aws.credentials.provider    org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider

# --- Extra JARs (JDBC + S3A) ---
# Spark tự load các JAR này khi khởi động — không cần khai báo lại trong code.
spark.jars                                      /opt/spark/custom_jars/mssql-jdbc-12.4.2.jre11.jar,/opt/spark/custom_jars/hadoop-aws-3.3.4.jar,/opt/spark/custom_jars/aws-java-sdk-bundle-1.12.262.jar,/opt/spark/custom_jars/postgresql-42.7.3.jar

# --- Performance Tuning (cơ bản) ---
spark.sql.shuffle.partitions                    4
spark.default.parallelism                       4

# --- S3A Committer (Fix FileNotFoundException) ---
spark.hadoop.fs.s3a.committer.name              directory
spark.sql.sources.commitProtocolClass           org.apache.spark.internal.io.cloud.PathOutputCommitProtocol
spark.sql.parquet.output.committer.class        org.apache.spark.internal.io.cloud.BindingParquetOutputCommitter